//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Pages {
    
    private PagesPage[] pageField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Page")]
    public PagesPage[] Page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PagesPage {
    
    private string pagesizeField;
    
    private string conditionField;
    
    private System.Nullable<bool> overflowField;
    
    private bool overflowFieldSpecified;
    
    private PagesPageImage imageField;
    
    private PagesPageZone[] zonesField;
    
    private ushort pagenumberField;
    
    /// <remarks/>
    public string Pagesize {
        get {
            return this.pagesizeField;
        }
        set {
            this.pagesizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Condition {
        get {
            return this.conditionField;
        }
        set {
            this.conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> Overflow {
        get {
            return this.overflowField;
        }
        set {
            this.overflowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OverflowSpecified {
        get {
            return this.overflowFieldSpecified;
        }
        set {
            this.overflowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PagesPageImage Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Zone", IsNullable=false)]
    public PagesPageZone[] Zones {
        get {
            return this.zonesField;
        }
        set {
            this.zonesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Pagenumber {
        get {
            return this.pagenumberField;
        }
        set {
            this.pagenumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PagesPageImage {
    
    private string imagenameField;
    
    private ushort xstartField;
    
    private ushort xEndField;
    
    private ushort yStartField;
    
    private ushort yEndField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Imagename {
        get {
            return this.imagenameField;
        }
        set {
            this.imagenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Xstart {
        get {
            return this.xstartField;
        }
        set {
            this.xstartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort XEnd {
        get {
            return this.xEndField;
        }
        set {
            this.xEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort YStart {
        get {
            return this.yStartField;
        }
        set {
            this.yStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort YEnd {
        get {
            return this.yEndField;
        }
        set {
            this.yEndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PagesPageZone {
    
    private PagesPageZonePart[] partsField;
    
    private string zonenameField;
    
    private ushort xstartField;
    
    private ushort xEndField;
    
    private ushort yStartField;
    
    private ushort yEndField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Part", IsNullable=false)]
    public PagesPageZonePart[] Parts {
        get {
            return this.partsField;
        }
        set {
            this.partsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Zonename {
        get {
            return this.zonenameField;
        }
        set {
            this.zonenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Xstart {
        get {
            return this.xstartField;
        }
        set {
            this.xstartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort XEnd {
        get {
            return this.xEndField;
        }
        set {
            this.xEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort YStart {
        get {
            return this.yStartField;
        }
        set {
            this.yStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort YEnd {
        get {
            return this.yEndField;
        }
        set {
            this.yEndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PagesPageZonePart {
    
    private string partnameField;
    
    private ushort xstartField;
    
    private ushort xEndField;
    
    private ushort yStartField;
    
    private ushort yEndField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Partname {
        get {
            return this.partnameField;
        }
        set {
            this.partnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort Xstart {
        get {
            return this.xstartField;
        }
        set {
            this.xstartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort XEnd {
        get {
            return this.xEndField;
        }
        set {
            this.xEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort YStart {
        get {
            return this.yStartField;
        }
        set {
            this.yStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort YEnd {
        get {
            return this.yEndField;
        }
        set {
            this.yEndField = value;
        }
    }
}
